{{ if .Values.jobs.cleanupMedia.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "mastodon.fullname" . }}-cleanup-unused-media
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.jobs.cleanupMedia.schedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ include "mastodon.fullname" . }}-cleanup-unused-media
          {{- with .Values.jobs.annotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cleanup-unused-media
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - bash
                - -c
                - "bin/tootctl media remove --days={{ .Values.jobs.cleanupMedia.days | default 7 }}"
              envFrom:
                - configMapRef:
                    name: {{ include "mastodon.fullname" . }}-env
                - secretRef:
                    name: {{ include "mastodon.fullname" . }}-secrets-env
              resources:
                {{- toYaml .Values.jobs.cleanupMedia.resources | nindent 16 }}
{{ end }}
