{{ if .Values.jobs.cleanupMediaProfiles.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "mastodon.fullname" . }}-cleanup-unused-media-profiles
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.jobs.cleanupMediaProfiles.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ include "mastodon.fullname" . }}-cleanup-unused-media-profiles
          {{- with .Values.jobs.annotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "mastodon.labels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          serviceAccountName: {{ include "mastodon.serviceAccountName" . }}
          containers:
            - name: cleanup-unused-media-profiles
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - bash
                - -c
                - "bin/tootctl media remove --days={{ .Values.jobs.cleanupMediaProfiles.days | default 7 }} --prune-profiles"
              envFrom:
                - configMapRef:
                    name: {{ include "mastodon.fullname" . }}-env
                - secretRef:
                    name: {{ include "mastodon.fullname" . }}-secrets-env
              {{- if .Values.configuration.search.enabled }}
              env:
                - name: ES_PASS
                  valueFrom:
                    secretKeyRef:
                      key: {{ .Values.configuration.search.password.secretKeyRef.key }}
                      name: {{ .Values.configuration.search.password.secretKeyRef.name }}
              {{- end }}
              resources:
                {{- toYaml .Values.jobs.cleanupMediaProfiles.resources | nindent 16 }}
{{ end }}
