apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
    app: {{ include "mastodon.fullname" . }}
    version: {{ .Chart.AppVersion | quote }}
  name: {{ include "mastodon.fullname" . }}-web
spec:
  selector:
    matchLabels:
      {{- include "mastodon.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
      app: {{ include "mastodon.fullname" . }}
      version: {{ .Chart.AppVersion | quote }}
  strategy:
    {{- toYaml .Values.web.strategy | nindent 4 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mastodon.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
        app: {{ include "mastodon.fullname" . }}
        version: {{ .Chart.AppVersion | quote }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - command:
            - bundle
            - exec
            - puma
            - -C
            - config/puma.rb
          env:
            - name: PORT
              value: "3000"
          envFrom:
            - configMapRef:
                name: {{ include "mastodon.fullname" . }}-env
            - secretRef:
                name: {{ include "mastodon.fullname" . }}-secrets-env
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: web
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          {{- if .Values.configuration.databaseReplicas }}
          {{- if .Values.configuration.databaseReplicas.enabled }}
          volumeMounts:
            - name: db-config-override
              mountPath: /opt/mastodon/config/database.yml
              subPath: database.yml
          {{- end }}
          {{- end }}
          readinessProbe:
            {{- toYaml .Values.web.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.web.startupProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      restartPolicy: Always
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "mastodon.serviceAccountName" . }}
      terminationGracePeriodSeconds: 30
      {{- if .Values.configuration.databaseReplicas }}
      {{- if .Values.configuration.databaseReplicas.enabled }}
      volumes:
        - name: db-config-override
          configMap:
            name: {{ include "mastodon.fullname" . }}-db-config-override
      {{- end }}
      {{- end }}
