{{- $fullName := include "mastodon.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.web.maxBodySize }}
    nginx.ingress.kubernetes.io/client-body-buffer-size: {{ .Values.ingress.web.maxBodySize }}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: {{ .Values.ingress.web.upstreamProxyTimeout | quote }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.ingress.web.upstreamProxyTimeout | quote }}
    nginx.ingress.kubernetes.io/proxy-send-timeout: {{ .Values.ingress.web.upstreamProxyTimeout | quote }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/service-upstream: "true"
    {{- if .Values.ingress.web.verifyClient.enabled }}
    nginx.ingress.kubernetes.io/auth-tls-secret: {{ .Values.ingress.web.verifyClient.secretName }}
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "false"
    {{- end }}
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
  name: {{ $fullName }}-web
spec:
  ingressClassName: {{ .Values.ingress.web.ingressClassName }}
  rules:
    - host: {{ .Values.ingress.web.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "mastodon.fullname" . }}-web
                port:
                  number: 3000
            path: /
            pathType: ImplementationSpecific
  tls:
    {{ .Values.ingress.web.tls | toYaml | nindent 4 }}
