{{ if .Values.keda.web.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
    scaledobject.keda.sh/name: {{ include "mastodon.fullname" . }}-web
  name: {{ include "mastodon.fullname" . }}-web
spec:
  cooldownPeriod: {{ .Values.keda.web.cooldownPeriod }}
  maxReplicaCount: {{ .Values.keda.web.maxReplicaCount }}
  minReplicaCount: {{ .Values.keda.web.minReplicaCount }}
  pollingInterval: {{ .Values.keda.web.pollingInterval }}
  scaleTargetRef:
    name: {{ include "mastodon.fullname" . }}-web
  {{- if .Values.keda.web.fallback.enabled }}
  fallback:
    replicas: {{ .Values.keda.web.fallback.replicas }}
    failureThreshold: {{ .Values.keda.web.fallback.failureThreshold }}
  {{- end }}
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "82"
  advanced:
    {{- if .Values.keda.web.advanced }}
    {{- toYaml .Values.keda.web.advanced | nindent 4 }}
    {{- end }}
{{ end }}
