{{ if .Values.keda.web.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
    scaledobject.keda.sh/name: {{ include "mastodon.fullname" . }}-web
  name: {{ include "mastodon.fullname" . }}-web
spec:
  cooldownPeriod: {{ .Values.keda.web.cooldownPeriod }}
  maxReplicaCount: {{ .Values.keda.web.maxReplicaCount }}
  minReplicaCount: {{ .Values.keda.web.minReplicaCount }}
  pollingInterval: {{ .Values.keda.web.pollingInterval }}
  scaleTargetRef:
    name: {{ include "mastodon.fullname" . }}-web
  {{- if .Values.keda.web.fallback.enabled }}
  fallback:
    replicas: {{ .Values.keda.web.fallback.replicas }}
    failureThreshold: {{ .Values.keda.web.fallback.failureThreshold }}
  {{- end }}
  triggers:
    - type: prometheus
      metadata:
        serverAddress: {{ .Values.keda.prometheusAddress }}
        metricName: access_frequency
        query: sum(rate(nginx_ingress_controller_requests{service="{{ include "mastodon.fullname" . }}-web"}[1m]))
        threshold: {{ .Values.keda.web.threshold | quote }}
        ignoreNullValues: {{ .Values.keda.web.ignoreNullValues | quote }}
    - type: memory
      metricType: Utilization
      metadata:
        value: "100"
  advanced:
    {{- if .Values.keda.web.advanced }}
    {{- toYaml .Values.keda.web.advanced | nindent 4 }}
    {{- end }}
{{ end }}
