{{- $context := . }}
{{- range .Values.onePassword }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  {{- if .suffix }}
  name: {{ include "mastodon.fullname" $context }}-{{ .suffix }}
  {{- else }}
  name: {{ .name }}
  {{- end }}
  {{- if .namespace }}
  namespace: {{ .namespace }}
  {{- end }}
spec:
  itemPath: {{ .itemPath }}
{{- end }}
