{{ if .Values.jobs.periodicWebRestart.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mastodon.fullname" . }}-restart-web-deployment
subjects:
- kind: ServiceAccount
  name: {{ include "mastodon.fullname" . }}-restart-web-deployment
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "mastodon.fullname" . }}-restart-web-deployment
  apiGroup: rbac.authorization.k8s.io
{{ end }}
