apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-operator
  namespace: argocd
spec:
  destination:
    namespace: elastic-system
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: eck-operator
    repoURL: https://helm.elastic.co
    targetRevision: 2.11.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
