apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastly-metrics
  namespace: argocd
spec:
  destination:
    namespace: fastly-metrics
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: prometheus-fastly-exporter
    helm:
      values: |
        existingSecret:
          name: "fastly-api-token"
          key: "fastly-api-token"

        serviceMonitor:
          enabled: true
          interval: 15s
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 0.2.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
