apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  destination:
    namespace: fluentbit
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: fluent-bit
    helm:
      values: |
        config:
          inputs: |
            [INPUT]
                Name http
                Listen 0.0.0.0
                Port 8080
          outputs: |
            [OUTPUT]
                name loki
                match *
                host loki-gateway.loki.svc.cluster.local
                port 80
                tenant_id tootcommunity
                remove_keys source
                labels job=fastly-cdn, fastly_host=$host
                line_format json
          service: |
            [SERVICE]
                Daemon Off
                Flush {{ .Values.flush }}
                Log_Level {{ .Values.logLevel }}
                Parsers_File parsers.conf
                Parsers_File custom_parsers.conf
                HTTP_Server On
                HTTP_Listen 0.0.0.0
                HTTP_Port {{ .Values.metricsPort }}
                Health_Check On

        dashboards:
          annotations: {}
          enabled: true
          labelKey: grafana_dashboard
          labelValue: 1
          namespace: monitoring

        extraPorts:
        - containerPort: 8080
          name: http-input
          port: 8080
          protocol: TCP

        ingress:
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/client-body-buffer-size: 50m
            nginx.ingress.kubernetes.io/proxy-body-size: 50m
            nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "false"
            nginx.ingress.kubernetes.io/auth-tls-secret: "tootcommunity/tootcommunity-ca-secret"
            nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
          enabled: true
          extraHosts:
          - host: fluent-bit.toot.community
            port: 8080
          ingressClassName: nginx
          tls:
          - hosts:
            - fluent-bit.toot.community
            secretName: fluent-bit.toot.community-tls

        kind: Deployment

        logLevel: info

        podDisruptionBudget:
          enabled: true
          minAvailable: 1

        prometheusRule:
          additionalLabels: {}
          enabled: true
          namespace: ""
          rules:
          - alert: NoOutputBytesProcessed
            annotations:
              message: |
                Fluent Bit instance {{ $labels.instance }}'s output plugin {{ $labels.name }} has not processed any
                bytes for at least 15 minutes.
              summary: No Output Bytes Processed
            expr: rate(fluentbit_output_proc_bytes_total[5m]) == 0
            for: 15m
            labels:
              severity: critical

        replicaCount: 3

        serviceMonitor:
          enabled: true
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: 0.36.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
