apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring
  syncPolicy:
    automated:
      selfHeal: true
  source:
    chart: grafana
    helm:
      values: |
        deploymentStrategy:
          type: Recreate # due to PVC

        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - monitoring.toot.community
          tls:
            - hosts:
                - monitoring.toot.community
              secretName: cf-origin-certificate-tls

        persistence:
          type: pvc
          enabled: true
          accessModes:
            - ReadWriteOnce
          size: 10Gi

        extraSecretMounts:
          - name: auth-oauth-secret-mount
            secretName: grafana-auth-oauth-secret
            defaultMode: 0440
            mountPath: /etc/secrets/auth_oauth
            readOnly: true

        grafana.ini:
          server:
            root_url: https://monitoring.toot.community
          auth.basic:
            enabled: false
          auth:
            disable_login_form: true
          auth.github:
            enabled: true
            allow_sign_up: true
            client_id: $__file{/etc/secrets/auth_oauth/client_id}
            client_secret: $__file{/etc/secrets/auth_oauth/client_secret}
            scopes: user:email,read:org
            auth_url: https://github.com/login/oauth/authorize
            token_url: https://github.com/login/oauth/access_token
            api_url: https://api.github.com/user
            allowed_organizations: toot-community
            role_attribute_path: contains(groups[*], '@toot-community/administrators') && 'GrafanaAdmin' || 'Viewer'
            allow_assign_grafana_admin: true
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.52.4
