apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  destination:
    namespace: loki
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: loki
    helm:
      values: |
        loki:
          storage:
            bucketNames:
              chunks: loki-toot-community
              ruler: loki-toot-community
              admin: loki-toot-community
            type: s3
            s3:
              s3: s3://loki-toot-community
              endpoint: https://ams3.digitaloceanspaces.com
              secretAccessKey: ${S3_SECRET_ACCESS_KEY}
              accessKeyId: ${S3_ACCESS_KEY}
              s3ForcePathStyle: false
              region: auto
              insecure: false

          compactor:
            working_directory: /var/loki/compactor
            shared_store: s3
            compaction_interval: 10m
            retention_enabled: true
            retention_delete_delay: 2h
            retention_delete_worker_count: 150

          limits_config:
            retention_period: 8760h

        read:
          extraArgs:
            - -config.expand-env=true
          extraEnv:
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-access-s3
                  key: key
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-access-s3
                  key: secret-key
          persistence:
            enableStatefulSetAutoDeletePVC: false

        write:
          extraArgs:
            - -config.expand-env=true
          extraEnv:
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-access-s3
                  key: key
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-access-s3
                  key: secret-key
          persistence:
            enableStatefulSetAutoDeletePVC: false

        backend:
          extraArgs:
            - -config.expand-env=true
          extraEnv:
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-access-s3
                  key: key
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-access-s3
                  key: secret-key
          persistence:
            enableStatefulSetAutoDeletePVC: false

        test:
          enabled: false

        monitoring:
          dashboards:
            enabled: false
          rules:
            enabled: false
            alerting: false
          serviceMonitor:
            enabled: false
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
          lokiCanary:
            enabled: false
            tolerations:
              - effect: NoSchedule
                key: limit
                operator: Equal
                value: db
              - effect: NoSchedule
                key: limit
                operator: Equal
                value: sidekiq
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 5.38.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
