apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring
  syncPolicy:
    automated:
      selfHeal: true
  source:
    chart: prometheus
    helm:
      values: |
        serviceAccounts:
          alertmanager:
            create: true
          nodeExporter:
            create: true
          pushgateway:
            create: false
          server:
            create: true
        alertmanager:
          enabled: true
          config:
            receivers:
              - name: 'default-receiver'
                webhook_configs:
                  - url: 'http://robusta-runner.robusta.svc.cluster.local/api/alerts'
                    send_resolved: true
            route:
              routes:
              - receiver: 'default-receiver'
                match_re:
                  severity: 'info|warn|error|critical'
                repeat_interval: 4h
                continue: true
        configmapReload:
          prometheus:
            enabled: true
        kubeStateMetrics:
          enabled: false
        nodeExporter:
          enabled: false
        server:
          enabled: true
          replicaCount: 1
          global:
            scrape_interval: 15s
            scrape_timeout: 10s
          persistentVolume:
            enabled: true
            size: 25Gi
          resources:
            requests:
              cpu: 50m
              memory: 2000Mi
          strategy:
            type: Recreate
        pushgateway:
          enabled: false
        prometheus-pushgateway:
          enabled: false
        prometheus-node-exporter:
          enabled: true
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 19.7.2
