apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tootcommunity
  namespace: argocd
spec:
  destination:
    namespace: tootcommunity
    server: https://kubernetes.default.svc
  project: mastodon
  source:
    helm:
      valueFiles:
      - values.yaml
    path: mastodon-chart
    repoURL: git@github.com:toot-community/kubernetes.git
    targetRevision: main
