apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  destination:
    namespace: velero
    server: https://kubernetes.default.svc
  project: infrastructure
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  source:
    chart: velero
    repoURL: https://vmware-tanzu.github.io/helm-charts/
    targetRevision: 5.0.1
    helm:
      values: |
        snapshotsEnabled: false
        deployNodeAgent: true

        resources:
          requests:
            cpu: 71m
            memory: 128Mi
          limits:
            memory: 512Mi

        nodeAgent:
          resources:
            requests:
              cpu: 1m
              memory: 176M
            limits:
              memory: 512Mi
          tolerations:
            - effect: NoSchedule
              key: limit
              operator: Equal
              value: db
            - effect: NoSchedule
              key: limit
              operator: Equal
              value: sidekiq

        configuration:
          defaultVolumesToFsBackup: true
          backupStorageLocation:
            - name: default
              provider: aws
              bucket: velero-toot-community
              config:
                region: auto
                s3Url: https://ams3.digitaloceanspaces.com

        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.7.1
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins

        credentials:
          useSecret: true
          existingSecret: cloud-credentials

        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
          prometheusRule:
            enabled: true
            spec:
              - alert: VeleroBackupPartialFailures
                annotations:
                  message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} partialy failed backups.
                expr: |-
                  velero_backup_partial_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
                for: 15m
                labels:
                  severity: warning
              - alert: VeleroBackupFailures
                annotations:
                  message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} failed backups.
                expr: |-
                  velero_backup_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
                for: 15m
                labels:
                  severity: warning

        extraObjects:
          - apiVersion: onepassword.com/v1
            kind: OnePasswordItem
            metadata:
              name: cloud-credentials
            spec:
              itemPath: "vaults/dhwqy3tub7zdwf2zj6cv4lprlu/items/pqvlwqwzf6vv37yzku6xiti3oq"

