apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  destination:
    namespace: velero
    server: https://kubernetes.default.svc
  project: infrastructure
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  source:
    chart: velero
    repoURL: https://vmware-tanzu.github.io/helm-charts/
    targetRevision: 3.1.5
    helm:
      values: |
        configuration:
          provider: aws

          backupStorageLocation:
            name: default
            bucket: velero-toot-community
            config:
              region: auto
              s3Url: https://0ae89288096e9795bb1a5d327d89aec5.r2.cloudflarestorage.com

          volumeSnapshotLocation:
            name: default
            provider: digitalocean.com/velero

        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.0.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins
          - name: digitalocean-plugin-for-velero
            image: digitalocean/velero-plugin:v1.1.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins

        credentials:
          useSecret: true
          existingSecret: cloud-credentials
          extraSecretRef: cloud-credentials-env

        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
          prometheusRule:
            enabled: true

        extraObjects:
          - apiVersion: onepassword.com/v1
            kind: OnePasswordItem
            metadata:
              name: cloud-credentials-env
            spec:
              itemPath: "vaults/dhwqy3tub7zdwf2zj6cv4lprlu/items/3zmgafrnm6e24x2kxlsskmpqhu"
          - apiVersion: onepassword.com/v1
            kind: OnePasswordItem
            metadata:
              name: cloud-credentials
            spec:
              itemPath: "vaults/dhwqy3tub7zdwf2zj6cv4lprlu/items/pqvlwqwzf6vv37yzku6xiti3oq"

