apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: datacenter
  namespace: fastly-metrics
spec:
  groups:
  - name: datacenter
    rules:

    ##
    ## Basic Transformations
    ## - counter -> rate
    ## - histogram -> latency
    ## - etc
    ##

    - record: fastly_datacenter:requests
      expr: sum(rate(fastly_rt_requests_total[120s])) by (datacenter)
    - record: fastly_datacenter:4xx_ratio
      expr: |
        sum(rate(fastly_rt_status_group_total{status_group="4xx"}[120s])) by (datacenter)
        / sum(rate(fastly_rt_status_group_total[120s])) by (datacenter)
    - record: fastly_datacenter:5xx_ratio
      expr: |
        sum(rate(fastly_rt_status_group_total{status_group="5xx"}[120s])) by (datacenter)
        / sum(rate(fastly_rt_status_group_total[120s])) by (datacenter)
    - record: fastly_datacenter:errors_ratio
      expr: |
        sum(rate(fastly_rt_errors_total[120s])) by (datacenter)
        / fastly_datacenter:requests
    - record: fastly_datacenter:latency_p50_seconds
      expr: histogram_quantile(0.5,sum(rate(fastly_rt_miss_duration_seconds_bucket[120s])) by (le,datacenter))
    - record: fastly_datacenter:latency_p99_seconds
      expr: histogram_quantile(0.99,sum(rate(fastly_rt_miss_duration_seconds_bucket[120s])) by (le,datacenter))

    ##
    ## Thresholds
    ## - Hysteresis, for more details see
    ##   https://promcon.io/2019-munich/talks/improved-alerting-with-prometheus-and-alertmanager/
    ##

    - record: fastly_datacenter:4xx_warn_ratio
      expr: |
        0.0375+0*count(fastly_datacenter:alerts_recently{alertname="fastlyDatacenter4xxPercent"}) by (datacenter)
        or 0.05+0*fastly_datacenter:requests
    - record: fastly_datacenter:5xx_warn_ratio
      expr: |
        0.0375+0*count(fastly_datacenter:alerts_recently{alertname="fastlyDatacenter5xxPercent"}) by (datacenter)
        or 0.05+0*fastly_datacenter:requests
    - record: fastly_datacenter:errors_warn_ratio
      expr: |
        0.0375+0*count(fastly_datacenter:alerts_recently{alertname="fastlyDatacenterErrorPercent"}) by (datacenter)
        or 0.05+0*fastly_datacenter:requests
    # 826ms would put you in the worst 20% of sites
    # Per https://www.littledata.io/average/server-response-time
    - record: fastly_datacenter:latency_p50_warn_seconds
      expr: |
        0.620+0*count(fastly_datacenter:alerts_recently{alertname="fastlyDatacenterP50Latency"}) by (datacenter)
        or 0.826+0*fastly_datacenter:requests
    # Our P50 latency, for example, tends to be less than one third of our P99 latency
    # Per https://medium.com/@djsmith42/how-to-metric-edafaf959fc7
    - record: fastly_datacenter:latency_p99_warn_seconds
      expr: |
        1.859+0*count(fastly_datacenter:alerts_recently{alertname="fastlyDatacenterP99Latency"}) by (datacenter)
        or 2.478+0*fastly_datacenter:requests

    ##
    ## Alert Status
    ##

    - record: fastly_datacenter:alerts
      expr: count(ALERTS{alertstate="firing", datacenter=~".+"}) by (alertname,datacenter)
    - record: fastly_datacenter:alerts_recently
      expr: sum(sum_over_time(ALERTS{alertstate="firing", datacenter=~".+"}[1h])) by (alertname,datacenter)

    ##
    ## Criteria
    ##

    # Notice: some minimum level of traffic over time
    - record: fastly_datacenter:criteria_notice
      expr: |
        min_over_time(fastly_datacenter:requests[5m]) > 1
        and count_over_time(fastly_datacenter:requests[5m]) > 2
    - record: fastly_datacenter:criteria_notice_recently
      expr: count_over_time(fastly_datacenter:criteria_notice[1h])

    # Warning: top 20% of notice
    - record: fastly_datacenter:criteria_warning
      #expr: |
      #  topk(
      #    scalar(
      #      count(fastly_datacenter:criteria_notice) * .2
      #    ), sum(fastly_datacenter:criteria_notice) by (datacenter)
      #  ) or count(fastly_datacenter:alerts_recently) by (datacenter)
      expr: |
        fastly_datacenter:criteria_notice > scalar(
          sum(fastly_datacenter:requests) * .01
        )
    - record: fastly_datacenter:criteria_warning_recently
      expr: count_over_time(fastly_datacenter:criteria_warning[1h])

    ##
    ## Alert Rules
    ## - Hold down timers / latch, for more details see
    ##   https://utcc.utoronto.ca/~cks/space/blog/sysadmin/PrometheusAlertmanagerFlapping
    ## - Example: max_over_time(min_over_time(fastly_datacenter:4xx_ratio[3m])[10m:15s])
    ##   - Once the event persists for 3m
    ##   - Hold down / latch for 10m
    ##

    - alert: fastlyDatacenter4xxPercent
      expr: |
        (
          max_over_time(
            min_over_time(fastly_datacenter:4xx_ratio[10m])[30m:15s]
          ) > fastly_datacenter:4xx_warn_ratio
        ) and (
          fastly_datacenter:criteria_warning_recently
          or count(fastly_datacenter:alerts_recently{alertname="fastlyDatacenter4xxPercent"}) by (datacenter)
        )
      labels:
        job: 'fastlyDatacenter'
        severity: warning
      annotations:
        description: 'High ({{- $value | humanizePercentage }})'
    - alert: fastlyDatacenter5xxPercent
      expr: |
        (
          max_over_time(
            min_over_time(fastly_datacenter:5xx_ratio[10m])[30m:15s]
          ) > fastly_datacenter:5xx_warn_ratio
        ) and (
          fastly_datacenter:criteria_warning_recently
          or count(fastly_datacenter:alerts_recently{alertname="fastlyDatacenter5xxPercent"}) by (datacenter)
        )
      labels:
        job: 'fastlyDatacenter'
        severity: warning
      annotations:
        description: 'High ({{- $value | humanizePercentage }})'
    - alert: fastlyDatacenterErrorPercent
      expr: |
        (
          max_over_time(
            min_over_time(fastly_datacenter:errors_ratio[10m])[30m:15s]
          ) > fastly_datacenter:errors_warn_ratio
        ) and (
          fastly_datacenter:criteria_warning_recently
          or count(fastly_datacenter:alerts_recently{alertname="fastlyDatacenterErrorPercent"}) by (datacenter)
        )
      labels:
        job: 'fastlyDatacenter'
        severity: warning
      annotations:
        description: 'High ({{- $value | humanizePercentage }})'
    - alert: fastlyDatacenterP50Latency
      expr: |
        (
          max_over_time(
            min_over_time(fastly_datacenter:latency_p50_seconds[10m])[30m:15s]
          ) > fastly_datacenter:latency_p50_warn_seconds
        ) and (
          fastly_datacenter:criteria_warning_recently
          or count(fastly_datacenter:alerts_recently{alertname="fastlyDatacenterP50Latency"}) by (datacenter)
        )
      labels:
        job: 'fastlyDatacenter'
        severity: warning
      annotations:
        description: 'High ({{- $value | humanizeDuration }})'
    - alert: fastlyDatacenterP99Latency
      expr: |
        (
          max_over_time(
            min_over_time(fastly_datacenter:latency_p99_seconds[10m])[30m:15s]
          ) > fastly_datacenter:latency_p99_warn_seconds
        ) and (
          fastly_datacenter:criteria_warning_recently
          or count(fastly_datacenter:alerts_recently{alertname="fastlyDatacenterP99Latency"}) by (datacenter)
        )
      labels:
        job: 'fastlyDatacenter'
        severity: warning
      annotations:
        description: 'High ({{- $value | humanizeDuration }})'
