{{ if .Values.keda.workers.enabled }}
{{- $context := . }}
{{- range .Values.keda.workers.queues }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    {{- include "mastodon.labels" $context | nindent 4 }}
    scaledobject.keda.sh/name: {{ include "mastodon.fullname" $context }}-sidekiq-{{ .name }}
  name: {{ include "mastodon.fullname" $context }}-sidekiq-{{ .name }}
spec:
  cooldownPeriod: {{ .cooldownPeriod | default $context.Values.keda.workers.cooldownPeriod }}
  minReplicaCount: {{ $context.Values.keda.workers.minReplicaCount }}
  maxReplicaCount: {{ $context.Values.keda.workers.maxReplicaCount }}
  pollingInterval: {{ .pollingInterval | default $context.Values.keda.workers.pollingInterval }}
  scaleTargetRef:
    name: {{ include "mastodon.fullname" $context }}-sidekiq-{{ .name }}
  {{- if $context.Values.keda.workers.fallback.enabled }}
  fallback:
    replicas: {{ $context.Values.keda.workers.fallback.replicas }}
    failureThreshold: {{ $context.Values.keda.workers.fallback.failureThreshold }}
  {{- end }}
  triggers:
    - type: prometheus
      metadata:
        serverAddress: {{ $context.Values.keda.prometheusAddress }}
        metricName: queue_latency
        query: avg(mastodon_sidekiq_queue_latency{queue="{{ .queue }}"})
        threshold: {{ .threshold | quote }}
        ignoreNullValues: {{ $context.Values.keda.workers.ignoreNullValues | quote }}
  advanced:
    {{- if $context.Values.keda.workers.advanced }}
    {{- toYaml $context.Values.keda.workers.advanced | nindent 4 }}
    {{- end }}
{{ end}}
{{ end }}
